name: Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *' # Every January 1 at 00:00 UTC
  workflow_dispatch:

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Update copyright year in index.html
        run: |
          year=$(date +"%Y")
          sed -i "s/© [0-9]\{4\}/© $year/g" src/index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/index.html
          git commit -m "chore: update copyright year to $year" || echo "No changes to commit"
          git push
